name: Build and push docker images

on:
  push:
    paths:
      - runtime/**
      - ray/**

jobs:
  docker:
    runs-on: ubuntu-latest
    # runs-on:
    #   group: Arc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Check changes
      #   uses: dorny/paths-filter@v3
      #   id: changes
      #   with:
      #     filters: |
      #       runtime:
      #         - 'runtime/**'
      #       ray:
      #         - 'ray/**'

      - name: Build compass runtime
        uses: docker/build-push-action@v6
        # if: steps.changes.outputs.runtime == 'true'
        with:
          context: runtime
          push: true
          tags: fengheai/compass-runtime:latest

      # - name: Build compass ray
      #   uses: docker/build-push-action@v6
      #   if: steps.changes.outputs.ray == 'true'
      #   env:
      #     RAY_VERSION: 2.46.0
      #   with:
      #     context: ray
      #     build-args: |
      #       RAY_VERSION=${{ env.RAY_VERSION }}
      #     push: true
      #     tags: fengheai/compass-ray:${{ env.RAY_VERSION }}
